start to-do back end , install first dependences for project   ,make …
mhmdwSamir/todo-backend pull request #1
Opened 2021-08-11 09:18 UTC by mhmdwSamir

…connection to mongodb , creat model for task

2021-08-20 19:05 UTC, a7md940 requested changes
Great job @mhmdwSamir, There's a few `requested changes`.

2021-08-20 19:05 UTC, ahmedradwan94 commented on controller/task.controller.js
> +      res.status(404).send(error);
Error handling is not correct.
your implementations says that: `if there's any type of error in the code in try {} block server will respond with HTTP status code 404 which means NOT_FOUND err`.
And actually it may occurs any type of error that's not a `NOT_FOUND`.

2021-08-20 19:05 UTC, ahmedradwan94 commented on controller/task.controller.js
> +        throw new Exception(
Great validation, good job man.

2021-08-20 19:05 UTC, ahmedradwan94 commented on controller/task.controller.js
> +      let task = new Task({ content, completed });
In create task we must not let the `client-app` to create new task with `{ completed: true }`.
so I'll expect from client-app to send me only the content and I'll create the task with status `{ completed: false }`.

2021-08-20 19:05 UTC, a7md940 commented on controller/task.controller.js
> +        throw new Exception(
Nice validation

2021-08-20 19:05 UTC, a7md940 commented on controller/task.controller.js
> +        throw new Exception(
Nice validation also.

2021-08-20 19:05 UTC, a7md940 commented on core/db/db.js
> +const mongoose = require("mongoose");
Please use **single** quote instead of **double** quotes.

2021-08-20 19:05 UTC, a7md940 commented on core/db/db.js
> +    .connect("mongodb://localhost/todoapp", {
You must get the mongoose `URI` from `process.env` environment variables.
so if you will to deploy this application in a host you should provide the MongoDB URI in environment variables.
example:
`await mongoose.connect(process.env.MONGO_URI);`

2021-08-22 08:43 UTC, a7mdRadwan requested changes
@mhmdwSamir  Please resolve the comments that you solved in your code.

2021-08-22 08:43 UTC, a7mdRadwan commented on app.js
> +app.listen(parseInt(process.env.PORT), () => {
the next time add a default value to protect your application from failure.
so if this env var not defined your application will work.
ex: `process.env.PORT != null ? parseInt(process.env.PORT) : 3000`.

2021-08-22 08:43 UTC, a7mdRadwan commented on app.js
> +app.use("/api", taskRouter);
it should be `/api/task`.

2021-08-22 08:43 UTC, a7mdRadwan commented on app.js
> +app.use("/api", userRouter);
it should be `/auth/user`

2021-08-25 22:25 UTC, merged